
services:
  db:
    image: postgres:14  # Use the latest official PostgreSQL image
    container_name: db_postgres2  # Name of the container
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}  # Name of the database
      POSTGRES_USER: ${POSTGRES_USER}  # Database user (corrected the key from POSTGRES_USERNAME to POSTGRES_USER)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Password for the user
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist PostgreSQL data


  catalog-service:
    image: lorenzo1897/catalog-service:latest
    container_name: catalog_service
    restart: always
    ports:
      - "8089:8080"  # Change this port if needed
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://db_postgres_service:5432/${POSTGRES_DB}  # Correct host (service name)
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db


    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      retries: 3

volumes:
  db_data:
