version: '3'

vars:
  GOOS: "{{default OS .GOOS}}"
  MVNW: '{{if eq .GOOS "windows"}}mvnw.cmd{{else}}./mvnw{{end}}'
  DC_DIR: "micro-servicess/docker-compose"
  MICRO_SERVICE_DC_FILE: "{{.DC_DIR}}/docker-compose.yaml"

tasks:
  default:
    cmds:
      - task: test

  test:
    deps: [format]
    cmds:
      - "{{.MVNW}} clean verify"

  format:
    cmds:
      - "{{.MVNW}} spotless:apply"

  build:
    cmds:
      - "{{.MVNW}} verify"

  start_docker:
    cmds:
      - docker compose -f "{{.MICRO_SERVICE_DC_FILE}}" up -d

  stop_docker:
    cmds:
      - docker compose -f "{{.MICRO_SERVICE_DC_FILE}}" down
      - docker compose -f "{{.MICRO_SERVICE_DC_FILE}}" rm -f

  restart_docker:
    cmds:
      - task: stop_docker
      - task: sleep
      - task: start_docker

  sleep:
    vars:
      DURATION: '{{default 5 .DURATION}}'
    cmds:
      - sleep {{.DURATION}}
