name: catalog-service

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./catalog-service

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Use OpenJDK via Eclipse Temurin distribution
          java-version: '21'
          cache: 'maven'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Ensure mvnw is executable
        run: chmod +x mvnw

      # Step 4: Lint with Spotless
      - name: Lint with Spotless (Check Only)
        run: ./mvnw spotless:check

      # Step 5: Automatically fix code style (Optional)
      # Uncomment this block to automatically fix formatting issues
      - name: Apply Code Formatting with Spotless
        if: always()
        run: ./mvnw spotless:apply

      # Step 6: Build the project and run tests
      - name: Build and Test
        run: ./mvnw clean verify

      # Step 7: Login to Docker Hub
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 8: Build and Publish Docker Images
      - name: Build and publish Docker Images
        if: github.ref == 'refs/heads/master'
        run: |
          ./mvnw spring-boot:build-image -DskipTests
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/catalog-service
